### ISSUE TITLE
Image Picker Problem 

### ISSUE THREAD

**Issue by SeniorTurkmen** [wilsonowilson/repaint#2]
Hi, 

When i try the picking an image the application is shut itself down before the image picker popup. 

I'm trying Desktop and web platforms.

I'm using ubuntu 20.04 lte

**Comment by wilsonowilson** [comment]
Ah I see. for desktop that's probably because of the file_selector_macos plugin only supporting macOS. I reckon there's a [file_selector_linux](https://pub.dev/packages/file_selector_linux) plugin that should fix that.

As for web, that's very odd. Could you tell me what browser and environment you're using?

**Comment by SeniorTurkmen** [comment]
Ow I installed the necessary plugins. I think the plugins are not working properly in ubuntu. I opened new issue on plugin repos

Many thanks for support
